name: Node.js CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - master

jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:dev
    - run: npm test

    - name: Setup Chrome Stable
      run: brew install --cask google-chrome-stable

    - name: Send email on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: "Build failure"
        to: ${{ secrets.MAIL_USERNAME }}
        from: "Discogs Enhancer <discogs.enhancer@gmail.com>"
        body: "The build has failed. Check the logs for more details."
